name: day_to_day
description: An app for creating daily routine.
author: Souvik Biswas

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_statusbar_manager: ^1.0.2
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/dtd_ic.png"

flutter:

  uses-material-design: true

  assets:
   - assets/robot.gif
  
  fonts:
    - family: BalooChettan
      fonts:
        - asset: fonts/BalooChettan-Regular.ttf
  
    - family: ConcertOne
      fonts:
        - asset: fonts/ConcertOne-Regular.ttf